### ISSUE TITLE
ajuda com query filter

### ISSUE THREAD

**Issue by gabihassan** [guialmorim/restapi-using-mongodb#1]
olá, boa noite.
eu gostaria de saber como implementar uma busca por keyword
exemplo:
localhost:8080/api/usuarios?email=gabriela

e depois disso listar os usuarios com nome de gabriela...

**Comment by guialmorim** [comment]
Boa tarde! depende um pouco da estrutura do seu banco mas você poderia usar uma query string para pegar o e-mail pela URL.
Você pode usar duas libs que ajudam nisso, o `react-router-dom` e o `query-string`
Ai se sua URL fosse essa: `localhost:8080/api/usuarios?email=gabriela` e você fizesse um `console.log(this.props.location.search)` iria obter todos os parâmetros na URL, no caso, `email=gabriela`

Ai usando a lib `query-string` ficaria mais ou menos assim:

```
import queryString from 'query-string'
...
componentDidMount() {
  const values = queryString.parse(this.props.location.search)
  console.log(values.email) // "gabriela"
}
```

Depois na query do mongoose você passaria essa variável como parâmetro no método `find()`

```
// Using async/await
const arr = await Usuario.find({ email: values.email });
```

nessas duas páginas estão detalhados melhor como usar a query string e o metodo `find()` do mongoose:
[](https://ui.dev/react-router-v4-query-strings/)
[](https://thecodebarbarian.com/how-find-works-in-mongoose)

Espero ter ajudado!
Abraço!

**Comment by gabihassan** [comment]
Olá, boa noite.
De uma forma geral você me ajudou, agradeço muito a você.

Obrigada, 
Gabi Hassan.
